# Generated by Django 5.0.6 on 2024-06-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileappcore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobileNo',
            new_name='mobile_No',
        ),
    ]
